version: "3.4"

services:
  service:
    build:
      dockerfile: "Dockerfile"
      context: "backend"
    image: "energy-hub/service"
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/app"
    networks:
      - "energy-hub"

networks:
  energy-hub:
